### ISSUE TITLE
JSON-LD should roundtrip back to into valid NeXML

### ISSUE THREAD

**Issue by cboettig** [cboettig/nexld#2]
This will require attention to node order; as @rvosa points out:

> I've had the issue that the different top-level blocks (taxa, trees, characters) were not in the input order after round-tripping, because the element of each of these blocks had become a key, and the keys were randomized. This is no good because then references to things might come before the thing that is being referenced and that is a hassle to code against, which is why the schema has been designed to avoid that. Similarly, nodes should precede edges within the tree element.

**Comment by rvosa** [comment]
What I meant, more or less, is the following:
`<nexml><otus/><trees/></nexml>`
Can, but must not, become:
`{nexml:{trees:[],otus:[]}}`
I have had this happen with a badgerfish xml2json mapper and it's no good because tree blocks reference otus blocks and this way the reference precedes the thing that it references. The schema was designed to avoid that.

**Comment by hlapp** [comment]
> I have had this happen with a badgerfish xml2json mapper and it's no good because tree blocks reference otus blocks and this way the reference precedes the thing that it references.

I don't think this matters at all in JSON. Unless someone wanted to use a stream-based event parser for JSON, and I don't think the data lends itself to that for practical use-cases. For example, RNeXML reads the whole NeXML file into memory as well, and there's really no way around that for any of the use-cases that it's designed for.

So I think the problem really matters only for re-serializing from JSON-LD to XML. I don't think it's a practically relevant limitation if you can't implement this in a way that would take what comes in through the input stream and write out immediately to the output stream. A serializer that writes NeXML from in-memory data (whether in JSON, or another representation) has to know anyway what part to write in which order, because unlike for JSON or JSON-LD, a NeXML file can be validated against the schema as to whether there are dangling references when read in order.

**Comment by cboettig** [comment]
Right, I'm with you there in that when we round-trip back into XML, we don't want to have:

```
<nexml><trees></trees><otus></otus></nexml>
```

for precisely the reason you mention: it is a pain for the developer consuming NeXML if the reference precedes the thing that it references.  However, I believe the ordering is not an issue for the developer consuming the JSON-LD version directly, because JSON-LD offers a more natural strategy to deal with references by using [Framing](https://json-ld.org/spec/latest/json-ld-framing/).  

The linked data is a graph which can be represented by many alternate JSON tree structures; framing exists so the developer gets their predictable, preferred JSON tree.

For instance, in my frame, I can simply request all references are embedded into the JSON tree.  Then if I want to know, say, what taxon is found on the end of some edge, instead of having to do any dictionary stuff to find the node which has my id given by target, and then which otu has the id given by node otu, and then look up the otu label, I can just exploit the JSON tree structure in my programming because it is already become nested thanks to the frame: `edge.target.otu.label`.   (this makes the file larger, but it can also then be worked on in streaming mode if desired)

**Comment by rvosa** [comment]
Right, agreed, this is only relevant when going back to XML.

**Comment by cboettig** [comment]
Okay, we can now round trip and validate the result, at least on the current range of test files: https://github.com/cboettig/nexld/tree/master/inst/test_nexml

See tests: https://github.com/cboettig/nexld/blob/67c4f2ee8d1eb2b062aa28b810400a729b5a101b/tests/testthat/test-validate.R#L3-L20
