### ISSUE TITLE
`xml:base` elements should be mapped into "@context": { "@base": "http://example.org/"}

### ISSUE THREAD

**Issue by cboettig** [cboettig/nexld#5]
**NOTE**: Updated title of issue to better reflect actual change that should be taken, see bottom of thread.  

----

Currently we just take the element attribute `id` as `@id`.  This works fine, though technically `@id` should be typed as a URI and thus plain strings should not be valid.  

More subtly, sometimes an element id will use a real URI identifier, but fails to indicate it as such.  The [ontotrace.xml](https://github.com/cboettig/nexld/blob/master/inst/extdata/ontotrace.xml) example is a good illustration of this:  `otu` elements are given `obo` ids, but without namespaces, like so

```
    "otu": [
      {
        "@type": "otu",
        "@id": "VTO_0065870",
        "label": "Xenurobrycon macropus",
        "about": "#VTO_0065870",
        "dwc:taxonID": "http://purl.obolibrary.org/obo/VTO_0065870"
      },
```

while it's nice to know that the `@id` is Darwin Core taxonID `dwc:taxonID`, this node has a lot of redundant information. Something like:

```
    "otu": [
      {
        "@type": "otu",
        "@id": "obo:VTO_0065870",
        "label": "Xenurobrycon macropus"
      },
```

should be sufficient (with `obo` URI defined in the `@context`); though perhaps it wise to keep track of the relationship `dwc:taxonID` as well).

**Comment by rvosa** [comment]
I like the more concise option, though I think we should reason this through very carefully to make sure we get this right. 

Just for background, the `@id` attribute of an element in XML is implicitly the final segment of a URI that starts with the base URI of the document, which might be its real location or something that is specified in the document using the `@xml:base` attribute.

So, for example, if you transform a NeXML document to RDF, the subjects of the generated triples are identified by this, now explicitly expanded, URI. This might be something like `file:///path/to/document.xml#` + the `@id` value. If you do the RDF transformation online, e.g. from a NeXML document served up by TreeBASE, the URI becomes something that begins with the domain name from whence the document originates.

Here's an example:
- [taxa.xml](https://github.com/nexml/nexml/blob/master/examples/taxa.xml) - note the explicit [xml:base](https://www.w3.org/TR/xmlbase/) attribute
- [taxa.rdf](https://github.com/nexml/nexml/blob/master/examples/taxa.rdf) - the resulting rdf, note the `@about` attributes, which now have a full URI

Because we want to be able to construct graphs of globally uniquely identifiable Things on the semantic web, we should ensure that the JSON-LD also, at least optionally, produces such fully qualified URIs. In the case that you are showing, this probably means that: 

1. somewhere closer to the root there should be the equivalent of an `xmlns:obo` statement that 
   binds a namespace URI to the `obo` prefix, i.e. in the `@context`
2. somehow the `@id` attribute is recognized as a CURIE that can be expanded into the fully
   qualified name (`obo:VTO_0065870` => `http://purl.obolibrary.org/obo/VTO_0065870`) and
   trimmed to become an NCName (`obo:VTO_0065870` => `VTO_0065870`) so that it can be 
   validly used in a round-tripped document as an XML id, which must be "a non-colonized name".

**Comment by cboettig** [comment]
@rvosa agree :100:%.  JSON-LD follows the same rules, e.g. if [I jsonld-expand this prototype](http://tinyurl.com/y9fnwsws) you'll see it's done the same thing you describe:

```
 "http://www.nexml.org/2009/otu": [
          {
            "@id": "https://json-ld.org/playground/t1",
            "@type": [
              "http://www.nexml.org/2009/otu"
            ],
            "http://www.nexml.org/2009/label": [
              {
                "@value": "species 1"
              }
            ]
          }

```

where we see ` "@id": "https://json-ld.org/playground/t1"` because it's taken the document URL as the base.  (Same if we render this into RDF as nquads in the Playground).  

I didn't realize XML required ids to be trimmed NCNames (if I'm getting the vocabulary correct?)  That does make it tricky to recognize when an id is something we can expand (like `obo`) and when it is really just local, like `n1`.  

JSON-LD does let us specify a `@base` for IRIs: <https://json-ld.org/spec/latest/json-ld/#base-iri> as part of the `@context`, so in the example above we could technically just include an `"@base": "http://purl.obolibrary.org/obo/"` if we had some way of determining that all ids were using this base URI....  (I think you can have multiple `@contexts` with different `@base` defaults if necessary, but that is getting messy).

**Comment by rvosa** [comment]
> I didn't realize XML required ids to be trimmed NCNames (if I'm getting the vocabulary correct?) 

Yeah, it has to be an NCName: https://www.w3.org/TR/xml-id/#processing

> That does make it tricky to recognize when an id is something we can expand (like obo) and when it is really just local, like n1.

Unfortunately, yes. And I don't think we want to do some non-idiomatic overloading of the value. Should there perhaps a separate attribute for when it's a CURIE?

> I think you can have multiple @contexts with different @base defaults if necessary, but that is getting messy

Technically, the value of `@xml:base` that is used is the one from the nearest ancestor-or-self, so that's actually somewhat similar (and messy).

**Comment by cboettig** [comment]
Ok, so to sum up, I think we need to alter the current behavior wrt to the id elements, which are implicit / local IRIs already after all.  Currently the R package will just stick the NCName it finds as the `@id` in the JSON-LD, and this behaves semantically exactly as it does in the XML, with reference to the local document.  

For any element that defines an `@xml:base`, we should be mapping that to the JSON-LD property    ` "@context": { "@base": "http://example.org/"}`.  Then JSON-LD compaction will actually swallow up this second `@context` node and automatically expand all the `@id` elements of only the child nodes, obeying the same rules as XML without being messy.  Pretty cool, check out this [playground example](http://tinyurl.com/ycahtw2y) (where the `otus` node id get expanded with their local `@base` without impacting the other `id`.  

For documents that want to use global IRIs in ids don't define the `xml:base` (Like that ontotrace NeXML, @hlapp !) we just let them behave as local IRIs.

Likewise, if we find a second IRI in `meta`, we just embed it as usual, without trying to do anything fancy.

**Comment by rvosa** [comment]
Ok, I think that's mostly great, except I am wondering how one might go
back to the XML world from JSON-DL without too many hacks. I mean, are
there any rules or patterns for decomposing a URI `http://example.org/t2`
into its namespace part `http://example.org/` and the local id `t2`?

**Comment by mtholder** [comment]
Not sure if I'm off-base, but I thought that the blank node convention `_:` in JSON-LD would be used for IDs  in JSON-LD that refer to things that are really local (like @rvosa's `n1` example above).

**Comment by gaurav** [comment]
I think that would work -- blank nodes are represented by node IDs in RDF/XML, so you can convert JSON-LD into RDF/XML and back while remembering which references are specific to this file and which are global. The RDF/XML also contains the predefined namespaces from JSON-LD, so in theory you could convert full URIs into short CURIEs. I [converted](https://gist.github.com/gaurav/43e0d95ab482bdd870c88cdc822451db) a JSON-LD file to RDF/XML and then back into JSON-LD and Turtle using rdfpipe on Windows, which does this correctly for XML -> Turtle conversions but not for XML -> JSON-LD.

**Comment by cboettig** [comment]
@rvosa I don't think any hacks are needed, I believe JSON-LD already has good 1:1 correspondence with the XML case here.  For instance, if you simply declare the `@base` as part of the context when you compact, then the URI ids will be decomposed back into local ids.  (Note that my playground example linked above compacted purely into NeXML vocab without setting a `@base`, hence the ids were expanded).  

And like @mtholder says, if there is no `@base` (like in the ontotrace.xml example), JSON-LD will do the natural thing with respect to local nodes.  As mentioned above, In both XML and JSON-LD, these id's implicitly have the Document URL (i.e. will be http://json-ld.org/playground) when expanded or rendered to RDF.  

So I think the only upshot is that we should just remember to respect XML `xsi:base` declarations, if present, as JSON-LD `@base`, and be careful about the context we use to compact, and we should be fine.  (Alternately, we can just ignore `xsi:base` and still be basically okay, just with doc-specific URIs -- not sure how many NeXML documents declare an `xsi:base` anyhow.  @rvosa Are any bothering to do that when they use CURIEs as `id` elements to make it clear they are global URIs?

**Comment by rvosa** [comment]
Ok, this all sounds good. Honestly, I'm not sure I've seen a lot of
`xml:base` malarkey in the wild so it should be fine, I guess?

**Comment by sckott** [comment]
@cboettig  did we sort this out already with #11 ?

**Comment by cboettig** [comment]
Basically yes, so I'm closing this.  

Technically no, because an xsi:base attribute can technically appear on any xml element in the NeXML document, and I believe that #11 only deals with it if it is on the nexml element.  If we added `base` to the list of JSON-LD special attributes here: https://github.com/cboettig/nexld/blob/master/R/as_list.R#L157 that would take care of the edge case, but would be difficult to compact since it could mean different contexts in different parts of the document.  As @rvosa mentions, this probably doesn't really occur in the wild anyway, and even if it did not much actually breaks if we ignore it.  (since these just get treated as local ids then; which most NeXML parsers would probably be doing anyway).
